language: python

# Versions of Python
python:
    - 2.6
    - 2.7

# Versions of Django
env:
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7

# Install Dependencies
install:
    - pip install django==$DJANGO
    - pip install -r test_requirements.txt

# Exclude python 2.6 and Django 1.7 as it is not supported by Django
matrix:
    exclude:
        - env: DJANGO=1.7
          python: 2.6

# Run tests
script:
    - python manage.py test
